import type { Dispatch, SetStateAction, ReactNode, RefObject } from "react";
import type { Food, Ingredient, Meal, PilotState, Feedback } from "../pilot";
import type { ScannerMode } from "../types";

export type Tab = "home" | "journey" | "plan" | "me" | "clients" | "meal" | "chef" | "foods" | "recipes" | "notes" | "more";
export type MenuSection = "list" | "me" | "profile" | "goal" | "life" | "week" | "shop" | "coach" | "account" | "support" | "about" | "evals";
export type Step = "in" | "recipe" | "make" | "made" | "after";

export interface AppApi {
  state: PilotState;
  setState: Dispatch<SetStateAction<PilotState>>;
  setTab: (t: Tab) => void;
  foodsView: "foods" | "recipes";
  setFoodsView: (v: "foods" | "recipes") => void;
  setCamera: (v: boolean) => void;
  setMode: (m: ScannerMode) => void;
  blank: (name?: string, brand?: string, from?: string, barcode?: string) => void;
  setEditFrom: (from: string) => void;
  review: import("../cloud").NumbersReview | null;
  coachLabel: string;
  sendReview: (kept: import("../cloud").ReviewFinding[], summary: string, reply?: string) => Promise<void>;
  answerClientReview: (clientUid: string, status: "approved" | "change", note: string, prev: import("../cloud").NumbersReview) => Promise<void>;
  addFromDatabase: (code: string) => void;
  searchDatabase: (q: string) => Promise<DbProduct[]>;
  peekBarcode: (code: string) => Promise<DbProduct | null>;
  add: (f: Food) => void;
  updateItem: (id: string, patch: Partial<Ingredient>) => void;
  saveMeal: () => void;
  mix: (id?: string) => boolean;
  mixWith: (items: Ingredient[], id: string) => boolean;
  step: Step;
  setStep: (s: Step) => void;
  personalize: () => Promise<void>;
  lookup: (code?: string) => Promise<void>;
  exportData: () => void;
  notify: (s: string) => void;
  setError: (s: string) => void;
  setBusy: (s: string) => void;
  api: (url: string, body?: unknown) => Promise<any>;
  setImage: (s: string) => void;
  setEdit: (f: Food | null) => void;
  setGoalsOpen: (v: boolean) => void;
  setAccessOpen: (v: boolean) => void;
  setReviewMeal: (m: Meal | null) => void;
  setFeedback: (f: { status: Feedback["status"]; taste: string; notes: string }) => void;
  setAdjustId: (s: string) => void;
  adjustId: string;
  limits: { maxWeight: string; minProtein: string; maxKcal: string };
  setLimits: (l: { maxWeight: string; minProtein: string; maxKcal: string }) => void;
  options: { food: Food; items: Ingredient[]; grams: number; explanation?: string }[];
  pending: { name: string; brand: string; values?: any }[];
  setPending: Dispatch<SetStateAction<{ name: string; brand: string }[]>>;
  barcode: string;
  setBarcode: (s: string) => void;
  query: string;
  setQuery: (s: string) => void;
  busy: string;
  services: { ai: boolean; airtable: boolean } | null;
  totals: ReturnType<typeof import("../pilot").aggregate>;
  pdRef: number | null;
  dayPd: number | null;
  // the kind of plate, from Today's What's cooking? or the Plate's own row; a saved recipe keeps it
  kind: import("../pilot").PlateKind;
  setKind: (k: import("../pilot").PlateKind) => void;
  moment: import("../moments").MomentId;
  setMoment: (m: import("../moments").MomentId) => void;
  usual: import("../moments").RhythmId[];
  setUsual: (ids: import("../moments").RhythmId[]) => void;
  region: import("../moments").RegionId | null;
  setRegion: (r: import("../moments").RegionId) => void;
  travelTo: import("../moments").RegionId | null;
  inbox: import("../cloud").InboxItem[];
  takeRecipe: (item: import("../cloud").InboxItem, how: "make" | "keep") => Promise<void>;
  dismissRecipe: (item: import("../cloud").InboxItem) => Promise<void>;
  personal: import("../personal").Personal;
  setPersonal: (p: import("../personal").Personal) => void;
  applyNumbers: (bandId: string, kcal: number, protein: number, method?: string, fats?: number, carbs?: number) => void;
  todayMacros: { kcal: number; protein: number; fats: number; carbs: number } | null;
  goalLog: import("../goal").GoalEntry[];
  addFoodPhoto: (foodId: string, dataUrl: string) => Promise<void>;
  saveFood: (f: import("../pilot").Food) => void;
  openFoodId: string | null;
  clearOpenFood: () => void;
  toggleFavorite: (foodId: string) => void;
  keepForLater: (meal: Meal, extra?: { photos?: string[]; prep?: Feedback["prep"]; status?: "prepared" | "not-used" }) => void;
  settleCard: (id: string, how: "eaten" | "not-used") => void;
  setFoodJob: (foodId: string, job: string | null) => void;
  eatenTodayKcal: number;
  dayName: string;
  tipGoalKey: string;
  requestTip: (foodId: string) => Promise<void>;
  removeFoodPhoto: (foodId: string, index: number) => void;
  setMainPhoto: (foodId: string, index: number) => void;
  mergeInLibrary: (keepId: string, otherId: string, name: string) => void;
  todayKcal: number | null;
  dayType: import("../personal").DayType;
  day: import("../personal").Day;
  setTodayPlan: (d: import("../plan").PlanDay | null) => void;
  setDated: (date: Date, d: import("../plan").PlanDay | null) => void;
  setDayType: (d: import("../personal").DayType) => void;
  formula: import("../personal").Formula | null;
  openMenu: (s?: MenuSection, from?: MenuSection) => void;
  newShared: number;
  markSharedSeen: () => void;
  setTravelTo: (r: import("../moments").RegionId | null) => void;
  matched: boolean;
  mealanCard: ReactNode;
  importRef: RefObject<HTMLInputElement | null>;
  goal: import("../goal").Goal | null;
  openGoal: () => void;
  openOut: () => void;
  closeOut: () => void;
  mealanAsk: number;
  mealanAsked: () => void;
  // the mix tip on a food card: code decides, the plate takes it, the helper hears what was wrong
  mixFor: (food: import("../pilot").Food) => import("../mixtip").MixTip;
  takeMix: (food: import("../pilot").Food, mix: import("../mixtip").Mix) => void;
  askAboutMix: (food: import("../pilot").Food, tip: import("../mixtip").MixTip) => void;
  mixQuestion: string | null;
  mixQuestionTaken: () => void;
  recordTalk: (q: string, reply: string, plate: string[]) => void;
  shareCard: (id: string, reason: "look" | "ok" | "help") => void;
  saveCardAsRecipe: (id: string) => void;
  setCarry: (id: string, how: "light" | "fine" | "heavy") => void;
  user: import("../cloud").CloudUser | null;
  cloudEnabled: boolean;
  cloudStatus: { ok: boolean; text: string; at?: string };
  profile: { role?: "coach"; coachId?: string; coachName?: string; coachEmail?: string; coachPhoto?: string; joinedAt?: string; coachSetAt?: string; formula?: "mifflin" | "katch" | null };
  joinCoach: (code: string) => Promise<void>;
  leaveCoach: () => Promise<void>;
  signOut: () => Promise<void>;
  deleteAccount: () => Promise<void>;
  // safety rules: the person's declarations, the AI switch, what the coach can confirm
  safety: import("../safety").Safety;
  ai: import("../safety").AiState;
  declareSafety: (patch: Partial<import("../safety").Safety>, record?: boolean) => void;
  flagFromModel: (situation: import("../safety").SituationId) => void;
  exportMyData: () => Promise<void>;
  deleteSteps: string;
  confirmClientAi: (clientUid: string, on: boolean) => Promise<void>;
  addStarter: () => void;
  importAirtable: () => Promise<void>;
  resetGoal: () => void;
  fitPd: (pd: number | null) => import("../goal").PdBand;
  fitDay: (pd: number | null) => import("../goal").PdBand;
  clientName: string;
  setClientName: (v: string) => void;
  coach: boolean;
  setCoach: (v: boolean) => void;
  filter: "all" | import("../goal").PdBand;
  setFilter: (f: "all" | import("../goal").PdBand) => void;
}

export type DbProduct = { code: string; name: string; brand: string; quantity: string; kcal: number | null; protein: number | null };
