// The whole nutrition table: add a line from the maker's website, see it on the card and on the plate.
const { chromium } = require("playwright");
const { spawn } = require("node:child_process");
const path = require("node:path"); const fs = require("node:fs");
const seed = JSON.parse(fs.readFileSync(path.resolve(__dirname, "seed.json"), "utf8"));
(async () => {
  const server = spawn(process.execPath, ["dist/server.cjs"], { cwd: path.resolve(__dirname, "../.."), env: { ...process.env, NODE_ENV: "production", PORT: "3189" }, stdio: ["ignore", "pipe", "pipe"] });
  await new Promise((r) => setTimeout(r, 2500));
  const b = await chromium.launch(process.env.CHROME ? { executablePath: process.env.CHROME } : {});
  const page = await b.newPage({ viewport: { width: 390, height: 1200 }, deviceScaleFactor: 2 });
  const errs = []; page.on("pageerror", (e) => errs.push(e.message));
  await page.addInitScript((s) => { if (!localStorage.getItem("seeded")) { localStorage.setItem("platemate-pilot-v1", JSON.stringify(s)); localStorage.setItem("chefmealan-goal", JSON.stringify({ band: "recomp", setBy: "you", setAt: "2026-10-01T08:00:00Z", source: "quick" })); localStorage.setItem("seeded", "1"); } }, seed);
  await page.goto("http://127.0.0.1:3189/"); await page.waitForTimeout(800);
  await page.locator("nav button").filter({ hasText: "Foods" }).click(); await page.waitForTimeout(300);
  await page.locator(".name-link, .row-text b").filter({ hasText: "Nutella" }).first().click(); await page.waitForTimeout(300);
  await page.getByRole("button", { name: "Review the label" }).click(); await page.waitForTimeout(400);
  const order = await page.locator(".modal .lt-row .lt-name").allTextContents();
  const okOrder = order.join("|") === "Energy|Fat|Carbohydrate|Fibre|Protein";
  console.log(okOrder ? "ok   review in label order" : "FAIL order " + order.join(", ")); if (!okOrder) process.exitCode = 1;
  await page.getByRole("button", { name: /Add a line/ }).click();
  await page.getByLabel("Which line").selectOption("sugars");
  await page.getByPlaceholder("Amount").fill("56.3");
  await page.getByRole("dialog").getByRole("button", { name: "Add", exact: true }).click(); await page.waitForTimeout(200);
  await page.getByRole("button", { name: /Add a line/ }).click();
  await page.getByLabel("Which line").selectOption("salt");
  await page.getByPlaceholder("Amount").fill("0.107");
  await page.getByRole("dialog").getByRole("button", { name: "Add", exact: true }).click(); await page.waitForTimeout(200);
  const after = await page.locator(".modal .lt-row .lt-name").allTextContents();
  const placed = after.findIndex((x) => /sugars/.test(x)) === after.findIndex((x) => /^Carbohydrate/.test(x)) + 1 && /Salt/.test(after[after.length - 1]);
  console.log(placed ? "ok   added lines sit where the label puts them" : "FAIL placement " + after.join(", ")); if (!placed) process.exitCode = 1;
  await page.getByLabel(/I checked the values/).check();
  await page.getByRole("button", { name: /Confirm & save food/ }).click(); await page.waitForTimeout(500);
  await page.locator(".name-link, .row-text b").filter({ hasText: "Nutella" }).first().click(); await page.waitForTimeout(300);
  const card = await page.locator(".label-table-read .lt-name").allTextContents();
  const onCard = card.some((x) => /sugars · added by you/.test(x)) && card.some((x) => /Salt/.test(x));
  console.log(onCard ? "ok   the card shows the whole table, marked added by you" : "FAIL card " + card.join(", ")); if (!onCard) process.exitCode = 1;
  console.log(errs.length ? "FAIL page errors: " + errs : "no page errors");
  await b.close(); server.kill();
})();
